# GET  request to validate token
GET http://localhost:4004/auth/validate
Authorization: Bearer {{token}}


# eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlckB0ZXN0LmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc0OTc0MjMzNCwiZXhwIjoxNzQ5Nzc4MzM0fQ.8k9Q-BIy2H2DG3efmp8-iScNvouS0whqLsloQABsP54